name: animated_gradient_box
description: A Flutter package that provides animated gradient borders for widgets with customizable colors, shapes, and animation controls.
version: 0.0.1
repository: https://github.com/YOUR_USERNAME/animated_gradient_border
homepage: https://github.com/YOUR_USERNAME/animated_gradient_border

environment:
  sdk: ^3.3.0
  flutter: ^3.24.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
