name: animated_gradient_box
description: A Flutter package that provides animated gradient borders for widgets with customizable colors, shapes, and animation controls.
version: 0.0.2
repository: https://github.com/woogi-kang/animated_gradient_box
homepage: https://github.com/woogi-kang/animated_gradient_box

environment:
  sdk: ^3.3.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

# Add these fields
issue_tracker: https://github.com/woogi-kang/animated_gradient_box/issues
documentation: https://github.com/woogi-kang/animated_gradient_box#readme
# You can also add topics/keywords for better discoverability
topics:
  - gradient
  - border
  - decoration
  - animated-border
  - gradient-border
